language: node_js

node_js:
  - "0.10"
  - "0.8"

env:
  - NUODB_HOME=/opt/nuodb NUODB_VERSION=2.1 NUODB_DOWNLOAD_URL=http://download.nuohub.org/nuodb_2.1.0.2.deb NUODB_ADD_DOMAIN_PASS=yes NUODB_START_AGENT=yes
  - NUODB_HOME=/opt/nuodb NUODB_VERSION=2.0.4 NUODB_DOWNLOAD_URL=http://download.nuohub.org/nuodb_2.0.4.20.deb NUODB_ADD_DOMAIN_PASS=no NUODB_START_AGENT=no
  - NUODB_HOME=/opt/nuodb NUODB_VERSION=2.0.3 NUODB_DOWNLOAD_URL=http://download.nuohub.org/nuodb-2.0.3.linux.x64.deb NUODB_ADD_DOMAIN_PASS=no NUODB_START_AGENT=no

notifications:
  recipients:
    - buck.robert.j@gmail.com
    - rbuck@nuodb.com
    - jgetto@nuodb.com
    - tgates@nuodb.com

before_install:
  - wget ${NUODB_DOWNLOAD_URL} --output-document=/var/tmp/nuodb.deb
  - sudo dpkg -i /var/tmp/nuodb.deb
  - if [[ "${NUODB_ADD_DOMAIN_PASS}" == "yes" ]] ; then sudo chmod 777 ${NUODB_HOME}/etc/default.properties; echo "domainPassword = bird" >> ${NUODB_HOME}/etc/default.properties; sudo chmod 600 ${NUODB_HOME}/etc/default.properties; fi
  - if [[ "${NUODB_START_AGENT}" == "yes" ]]; then sudo service nuoagent start; fi
  - sleep 10


before_script:
  - /opt/nuodb/bin/nuodbmgr --broker localhost --user domain --password bird --command "start process sm database test host localhost archive /var/opt/nuodb/production-archives/test initialize true waitForRunning true"
  - /opt/nuodb/bin/nuodbmgr --broker localhost --user domain --password bird --command "start process te database test host localhost options '--dba-user dba --dba-password goalie' waitForRunning true"
  - echo "create user cloud password 'user';" | ${NUODB_HOME}/bin/nuosql test@localhost --user dba --password goalie

after_script:
  - sudo dpkg -r nuodb
