language: node_js

node_js:
  - "0.10"
  - "0.8"
  - "0.6"

env:
  - NUODB_HOME=/opt/nuodb NUODB_VERSION=2.0.4
  - NUODB_HOME=/opt/nuodb NUODB_VERSION=2.0.3
  - NUODB_HOME=/opt/nuodb NUODB_VERSION=2.0.2
  - NUODB_HOME=/opt/nuodb NUODB_VERSION=2.0.1
  - NUODB_HOME=/opt/nuodb NUODB_VERSION=2.0
  - NUODB_HOME=/opt/nuodb NUODB_VERSION=1.2

notifications:
  recipients:
    - buck.robert.j@gmail.com
    - rbuck@nuodb.com
    - jgetto@nuodb.com
    - tgates@nuodb.com

before_install:
  - wget http://download.nuohub.org/nuodb-${NUODB_VERSION}.linux.x64.deb --output-document=/var/tmp/nuodb.deb
  - sudo dpkg -i /var/tmp/nuodb.deb
  - '[ "${TRAVIS_NODE_VERSION}" == "0.10" ] || npm install -g npm@1.4.28'
  - npm install -g npm@latest
  - sleep 2

before_script:
  - /opt/nuodb/bin/nuodbmgr --broker localhost --user domain --password bird --command "start process sm database test host localhost archive /var/opt/nuodb/production-archives/test initialize true waitForRunning true"
  - /opt/nuodb/bin/nuodbmgr --broker localhost --user domain --password bird --command "start process te database test host localhost options '--dba-user dba --dba-password goalie' waitForRunning true"
  - echo "create user cloud password 'user';" | ${NUODB_HOME}/bin/nuosql test@localhost --user dba --password goalie

after_script:
  - sudo dpkg -r nuodb
